# This has been made by ChatGPT since I don't want to bother making actions.

name: Build WPF App

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build project
        run: dotnet build --configuration Release --no-restore

      - name: Publish exe
        run: dotnet publish -c Release -r win-x64 --self-contained -p:PublishSingleFile=true -p:IncludeNativeLibrariesForSelfExtract=true

      - name: Prepare Release
        id: get_version
        run: |
          version=$(cat *.csproj | grep -oPm1 "(?<=<Version>)[^<]+")
          echo "version=$version" >> $GITHUB_ENV

      - name: Read CHANGELOG.md
        id: changelog
        run: |
          notes=$(cat CHANGELOG.md)
          echo "notes<<EOF" >> $GITHUB_ENV
          echo "$notes" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Create Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create temp-release --draft --title "Y10 Tools - ${{ env.version }}" --notes "${{ env.notes }}"

      - name: Upload Artifact to Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release upload temp-release "Y10_Tools\bin\Release\net8.0-windows\win-x64\publish\Y10_Tools.exe"
